### ISSUE TITLE
rename PlaylistGenresplit use case to CompleteYearSplit use case

### ISSUE THREAD

**Issue by finesden33** [finesden33/Songwarp#36]

**Comment by finesden33** [comment]
So basically, me and abhi realized spotify doesn't give genres
So we decided the only thing we can do as a 'split' is to split the playlist by its year of origin
but since only spotify has proper years (youtube's year is year of video publish, not actual song release)
The 'split' button on page 2 will first invoke the correct match use case (based on whatever playlist type is in the currentstate)
then it will invoke the completeYearSplit use case, which takes in the completePlaylist that was just made, as an input
and outputs a list of complete playlists

**Comment by mmahekk** [comment]
#40 took care of this issue, we can open up a new issue to handle this new use case
